src/components/PrioritiesPage/PrioritiesPage.jsx, src/components/QuestionsPage/QuestionsPage.jsx, src/components/UserPage/UserPage.jsx, src/components/WeekPage/WeekPage.jsx
=> new code comments

package.json, src/components/UserPage/UserPage.jsx, src/components/WeekTable/WeekTable.jsx
table is showing up on user home page just showing dummy data (not connected to database)
=> week table component

database.sql, server/routes/idealWeek.router.js, src/components/WeekPage/WeekPage.jsx, src/components/WeekPage/weekpage.css, src/redux/reducers/_root.reducer.js, src/redux/reducers/activities.reducer.js, src/redux/sagas/_root.saga.js, src/redux/sagas/fetchActivities.saga.js, src/redux/sagas/newActivity.saga.js
I'm sorry this is so much code, I'll do better
=> David week page

package.json, src/components/App/App.jsx, src/components/PrioritiesPage/PrioritiesPage.jsx
Fully functional priorities-ordering component.  MUI employed, but no styling done yet.
=> Feature krystal priorities page

src/components/QuestionsPage/QuestionsPage.jsx
Updated answers hook/dispatch to include question_id paired with each response.  Also removed categories fetch (now in app.jsx).
=> Questions page dispatch data update

src/components/PrioritiesPage/PrioritiesPage.jsx
Added MUI theme (applies brand font and colors).
Styled drag-n-drop list with blue/gray saturation gradient on MUI Boxes.
=> Krystal priorities MUI update

server/routes/userlist.router.js, server/server.js, src/components/AdminPage/AdminPage.jsx, src/redux/reducers/_root.reducer.js, src/redux/reducers/userlist.reducer.js, src/redux/sagas/_root.saga.js, src/redux/sagas/userlist.saga.js
**New files in the PR:**
- userlist.router.js (contains a GET route with admin protection)
- userlist.saga.js (contains a FETCH saga)
- userlist.reducer.js (contains one simple SET reducer for the list of all users)
**Updated files in the PR:**
- server.js (added userlist router)
- _root.saga.js (added userlist saga)
- _root.reducer.js (added userlist reducer)
- AdminPage.jsx
=> Krystal / Admin Page — Protected GET for all users, user list displayed on AdminPage

src/components/App/App.css, src/components/LoginForm/LoginForm.jsx, src/components/LoginPage/LoginPage.jsx, src/components/RegisterForm/RegisterForm.jsx, src/components/RegisterPage/RegisterPage.jsx
Also changed the CSS hover color on the text link from teal to blue.
Functionality is all same, just changed over to MUI theme/components.
=> Krystal - Register and Login Pages/Forms are MUI.

server/routes/introComplete.router.js, server/server.js, src/components/IntroPage/IntroPage.jsx, src/redux/sagas/user.saga.js
Added dispatch to button on IntroPage.
Added file: introComplete.router.js (contains PUT route which updates only this boolean value to true).
Added introComplete.router to server.js.
Added saga to user.saga.js.
=> Krystal introComplete dispatch/PUT router

package.json, src/components/WeekPage/WeekPage.jsx, src/components/WeekTable/WeekTable.jsx
=> Table logic ashlen

database.sql, server/routes/questionsComplete.router.js, server/server.js, src/components/QuestionsPage/QuestionsPage.jsx, src/redux/sagas/user.saga.js
- Added dispatch to button on QuestionsPage which makes boolean TRUE after first visit
- Buttons on QuestionsPage are conditionally rendered based on boolean
- Removed POST dispatch on QuestionsPage that was for testing purposes
- Created questionsComplete.router.js
- Added router to server.js
- Added worker saga to user.saga.js
- QuestionsPage now has MUI theme and minor updates to styling
=> questionsComplete boolean router/saga/dispatch, MUI theme in QuestionsPage

src/components/Footer/Footer.jsx
Updated footer to match existing product
=> David footer

server/routes/setupComplete.router.js, server/server.js, src/components/WeekPage/WeekPage.jsx, src/redux/sagas/user.saga.js
Changes to WeekPage:
- Added useHistory
- Grabbed user data from store
- Added click handler function with dispatch and push to /user
- Added DONE button that only shows the first time a user is here setting up their week
Other Updates:
- Created setupComplete.router and added it to server.js
- Added worker saga for this PUT route to user.saga.js
=> setupComplete route that fires off from WeekPage

src/components/AddActivityForm/AddActivityForm.jsx, src/components/WeekPage/WeekPage.jsx
=> David weekpage add visual

src/components/IntroPage/IntroPage.jsx, src/components/QuestionsPage/QuestionsPage.jsx, src/components/WeekPage/WeekPage.jsx
=> added copy

src/components/WeekPage/WeekPage.jsx
=> fixed styling issues

server/routes/idealWeek.router.js, src/components/WeekPage/WeekPage.jsx
This creates a join so that rank can be accessed through the activities GET, and sets styling on the weekpage in accordance with rank
=> David week router join

src/components/WeekTable/WeekTable.jsx
priorities listed in order, clean up code
=> Ashlen table styling

src/components/AdminPage/AdminPage.jsx, src/components/IntroPage/IntroPage.jsx, src/components/PrioritiesPage/PrioritiesPage.jsx, src/components/QuestionsPage/QuestionsPage.jsx, src/components/UserPage/UserPage.jsx, src/components/WeekPage/WeekPage.jsx
Added useLayoutEffect to:
IntroPage, QuestionsPage, PrioritiesPage, WeekPage, UserPage, and AdminPage
which makes these pages load scrolled to the top.
Also removed any unused imports on these components.
Included David's updated colors on WeekPage.
=> krystal_useLayoutEffect

src/components/IntroPage/IntroPage.jsx, src/components/LandingPage/LandingPage.jsx, src/components/QuestionsPage/QuestionsPage.jsx, src/components/UserPage/UserPage.jsx, src/components/WeekPage/WeekPage.jsx, src/components/WeekTable/WeekTable.jsx
=> finishing styling touches

database.sql, server/routes/question.router.js, src/components/ActivityModal/ActivityModal.jsx, src/components/AdminPage/AdminPage.jsx, src/components/App/App.jsx, src/components/EditQuestionsModal/EditQuestionsModal.jsx, src/components/EditQuestionsPage/EditQuestionsPage.jsx, src/redux/sagas/_root.saga.js, src/redux/sagas/editQuestions.saga.js
Added EditQuestionsPage with auth-protected PUT route, page accessible only through Admin page.  Updated styling in modals and on AdminPage.
=> Edit Questions Page, Finishing Touches
